const INCREMENT_COUNT = 'INCREMENT_COUNT';
const DECREMENT_COUNT = 'DECREMENT_COUNT';

const REQUEST_SUBREDDIT = 'REQUEST_SUBREDDIT';
const RECEIVE_SUBREDDIT = 'RECEIVE_SUBREDDIT';

export default {
  INCREMENT_COUNT,
  DECREMENT_COUNT,
  REQUEST_SUBREDDIT,
  RECEIVE_SUBREDDIT,
};
