// Apps
export const APP_FETCHING_BY_STORE_ID = 'APP_FETCHING_BY_STORE_ID';
export const APP_FETCH_SUCCESS = 'APP_FETCH_SUCCESS';
export const APP_FETCH_ERROR = 'APP_FETCH_ERROR';

// App.review
export const APP_REVIEW_FETCHING_BY_STORE_ID = 'APP_REVIEW_FETCHING_BY_STORE_ID';
export const APP_REVIEW_FETCHING_SUCCESS = 'APP_REVIEW_FETCHING_SUCCESS';
export const APP_REVIEW_CLEAR = 'APP_REVIEW_CLEAR';
export const APP_REVIEW_FETCHING_ERROR = 'APP_REVIEW_FETCHING_ERROR';
